version: '3'
services:
  my-postgres:
    container_name: my-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD:
      POSTGRES_DB: mekari
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: always
